version: '3.8'

services:
    app:
        container_name: shopify
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - 3000:3000
