import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'tippy.js/dist/tippy.css'; // optional
import 'react-quill/dist/quill.snow.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import ClientContext from '@/context/client-context';

const inter = Inter({ subsets: ['latin', 'vietnamese'], weight: ['100', '200', '300', '400', '500', '600', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ backgroundColor: '#ececec' }}>
                <ClientContext>{children}</ClientContext>
            </body>
        </html>
    );
}
